language: node_js
node_js:
  - '5.1'
before_script:
  - gem update --system
  - gem install compass
  - npm install -g bower grunt-cli karma-coverage coveralls
  - bower install
after_script:
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
